#Github WORKFLOW: The whle yml file
name: nightly-build-at-11pm
#Github action Components:
#Github EVENTS:  represents the activity that triggers reaction
on:
  schedule:
    - cron: '0 23 * * *' #runs every day at 23:00 https://jasonet.co/posts/scheduled-actions/

#Github JOBS: a set of steps running in sequence to complety a task, each job runs on its own runner. jobs run in paralell except if you use
# use the action "needs", in this case, it will execute in the sequel of the job specified in the front of "needs" action   
jobs:
  e2e-smoke-playwright-job: #name of the job
    timeout-minutes: 60 #how long it will run before stops to execute the job
    runs-on: ubuntu-latest # System where it will be executed
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy
    #GIhub STEPS: a github action or a script that will run on t he runner. Steps are executed in order
    #Runner is a machine that execute the job in a workflow
    steps:
    - uses: actions/checkout@v4 #clone repository
    - uses: actions/setup-node@v4
      with:
        node-version: lts/* #it will setup the latest version of node

    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test web/tests/loginTests.spec.ts --grep @smoke
      env:
        HOME: /root
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
